apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World, this is my first Chart."
  drink: {{ .Values.favoriateDrink }}
  salad: {{ .Values.global.salad }}